### ISSUE TITLE
I added the front end to the rest of the stuff

### ISSUE THREAD

**Issue by VivianLVenter** [thepickpocket/Networks_COS332#1]
I added the front end to the rest of the stuff. So from now on I think we need to work from the that folder :)

**Comment by VivianLVenter** [comment]
Dankie dit lyk flippen nice! Ek het net alles in die "Intellij" folder gesit sodat ons dit daar kan verander soos nodig*

**Comment by thepickpocket** [comment]
Ok ek dink ek is klaar met die game interface, kyk net hoe ek die eerste button A0 stuur en laat weet of ek dit moet verander, want ek is nie seker of dit gaan werk nie...

**Comment by VivianLVenter** [comment]
Die method van die buttons moet get wees nie post nie... en die url moet ?shoot wees nie

**Comment by thepickpocket** [comment]
Ok ekt daardie klein veranderings gemaak. As daar nog iets is wat ek nie reg gedoen het nie, skree maar :D Ek sal later vandag ook net 'n javascript file maak en begin met die animations...
Vertel my net, moet ek nou al die nuwe grid insit vir die multiplayer functionality? Want dit gaan verander aan die get uri soos miskien ?shoot=A0 vir die opponent grid en dan ?gotShot=A1 vir die player grid...

**Comment by VivianLVenter** [comment]
Laat ons eers die single reg kry dan kan ons mulitplayer doen... Want as daar issues kom met die game dan hoef ons net eers single player uit te sort :)

**Comment by VivianLVenter** [comment]
Hi, die uri vir die buttons moet dit wees: **onclick="location.href = 'shoot=A0';** sover werk dit reg en dan vir multiplayer kan ons net bylas getShot=A0

**Comment by VivianLVenter** [comment]
Oh en hoekom display die glypicons nie by my nie?

**Comment by thepickpocket** [comment]
oh ok so die <code>../game.html</code> moet uitgehaal word?
Ek verstaan nie hoekom die glyphicons nie by jou wys, nie...Het jy inspect element gedoen en gekyk of jy enige errors kry, want by my wys alles...

**Comment by VivianLVenter** [comment]
haha sal nou dit doen dan, jaw jy is reg die game.html ding moet uit... Ek is besig om al die functionality na 'n ander class te skuif... dit raak cluttered in the een file

**Comment by thepickpocket** [comment]
Ok dis doodreg, ek push nou die game file sonder die lang url...

**Comment by thepickpocket** [comment]
Ok ek het die probleem gekry met die icons wat nie render nie. Fontawesome soek dit locally en ons host die file op die server, ek is besig om te kyk hoe mens dit regmaak.

**Comment by VivianLVenter** [comment]
Okey dis reg, ek is besig ook om errors reg te maak die socket close heeltyd onverwags
