### ISSUE TITLE
8x8 Grid generation

### ISSUE THREAD

**Issue by VivianLVenter** [thepickpocket/Networks_COS332#4]
Okey ek generate the 8x8 grid maar vir een of ander rede by row 2 (1) gaan die laaste block in sy eie lyn... Run maar die server en stuff om te kyk wat hy doen. Ek weet nie hoekom hy dit doen nie...

**Comment by thepickpocket** [comment]
Just had a look. Ok as jy kyk na die web inspector, maak net seker dat jy in daardie spesifieke <code><tr> </code> die button add, want dit lyk asof jy die button add in sy eie <code><tr></code>
![webinspect](https://cloud.githubusercontent.com/assets/8138355/7666385/c69f563c-fbe3-11e4-8d50-7898ceba0fb4.jpg)

**Comment by thepickpocket** [comment]
Was net 'n copy en paste error. Ek push nou die update, dan kan jy sien waar die foutjie was :dart:
