### ISSUE TITLE
Winner Announcement Rank

### ISSUE THREAD

**Issue by VivianLVenter** [thepickpocket/Networks_COS332#6]
Ek het so bietjie gespeel en hy bly se ek is 'n commander maak nie saak wat my accuracy is nie... Ek dink nie die ding reset as 'n nuwe game begin nie...

**Comment by thepickpocket** [comment]
Ok will have a quick look at it and get it fixed.

**Comment by thepickpocket** [comment]
I adjusted the percentages you need to get to change ranking...It seems to work now. Also just initialized the hits and total hits variables when starting a new game...
